services:
  fastapi_app:
    build: .
    container_name: fastapi_app
    command: uvicorn config:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    depends_on:
      db:
        condition: service_healthy

#  streamlit_app:
#    build: .
#    container_name: streamlit_app
#    command: streamlit run app/app.py --server.port 8501 --server.address 0.0.0.0
#    ports:
#      - "8501:8501"
#    volumes:
#      - .:/app
#    environment:
#      - PYTHONPATH=/app
#    depends_on:
#      - fastapi_app

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Shunki970521
      MYSQL_DATABASE: mydb
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: Shunki970521
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
