"""init

Revision ID: 344b6a885b01
Revises: 
Create Date: 2026-07-23 10:26:46.545808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '344b6a885b01'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='users'
    )
    op.create_table('body_profiles',
    sa.Column('id', sa.Integer(), nullable=False, comment='主キー'),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('height', sa.String(length=3), nullable=False, comment='身長'),
    sa.Column('weight_kg', sa.String(length=3), nullable=False, comment='体重'),
    sa.Column('activity_status', sa.Enum('OFFICE', name='activity_status'), nullable=False, comment='生活レベル'),
    sa.Column('recorded_at', sa.Date(), nullable=False, comment='登録日'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='ユーザー身体情報'
    )
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_name', sa.String(length=10), nullable=False, comment='運動名'),
    sa.Column('calories_burned', sa.String(length=3), nullable=False, comment='消費カロリー'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('basal_calories', sa.String(length=4), nullable=False, comment='基礎代謝'),
    sa.Column('deficit', sa.String(length=4), nullable=False, comment='赤字カロリー'),
    sa.Column('protein', sa.String(length=3), nullable=False, comment='タンパク質'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intakes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('food_name', sa.String(length=20), nullable=False, comment='食事名'),
    sa.Column('calorie', sa.String(length=4), nullable=False, comment='カロリー'),
    sa.Column('protein', sa.String(length=2), nullable=False, comment='タンパク質'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intakes')
    op.drop_table('goals')
    op.drop_table('exercises')
    op.drop_table('body_profiles')
    op.drop_table('users')
    # ### end Alembic commands ###
