"""delete user table

Revision ID: 52b3938d30af
Revises: b687c362ed65
Create Date: 2026-03-22 01:11:47.294416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52b3938d30af'
down_revision: Union[str, Sequence[str], None] = 'b687c362ed65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='User ID(主キー)'),
    sa.Column('name', sa.String(length=20), nullable=False, comment='ユーザー名'),
    sa.PrimaryKeyConstraint('id'),
    comment='User'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
