"""init

Revision ID: a373b8f7501a
Revises: 
Create Date: 2026-02-23 01:30:55.025653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a373b8f7501a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='User ID(主キー)'),
    sa.Column('name', mysql.VARCHAR(length=20), nullable=False, comment='ユーザー名'),
    sa.PrimaryKeyConstraint('id'),
    comment='User',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='User',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
