"""init

Revision ID: b687c362ed65
Revises: 
Create Date: 2026-03-18 15:32:25.619893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b687c362ed65'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='User ID(主キー)'),
    sa.Column('name', sa.String(length=20), nullable=False, comment='ユーザー名'),
    sa.PrimaryKeyConstraint('id'),
    comment='User'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='users'
    )
    op.create_table('body_profiles',
    sa.Column('id', sa.Integer(), nullable=False, comment='主キー'),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('height', sa.String(length=3), nullable=False, comment='身長'),
    sa.Column('weight_kg', sa.String(length=3), nullable=False, comment='体重'),
    sa.Column('activity_status', sa.Enum('OFFICE', name='activity_status'), nullable=False, comment='生活レベル'),
    sa.Column('recorded_at', sa.Date(), nullable=False, comment='登録日'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='ユーザー身体情報'
    )
    op.create_table('daily_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ユーザーID'),
    sa.Column('date', sa.Date(), nullable=False, comment='日付'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_user_date')
    )
    op.create_index('ix_user_date', 'daily_records', ['user_id', 'date'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('basal_calories', sa.String(length=4), nullable=False, comment='基礎代謝'),
    sa.Column('deficit', sa.String(length=4), nullable=False, comment='赤字カロリー'),
    sa.Column('protein', sa.String(length=3), nullable=False, comment='タンパク質'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('daily_unit_id', sa.Integer(), nullable=False, comment='日単位のデータのID'),
    sa.Column('exercise_name', sa.String(length=10), nullable=False, comment='運動名'),
    sa.Column('calories_burned', sa.String(length=3), nullable=False, comment='消費カロリー'),
    sa.ForeignKeyConstraint(['daily_unit_id'], ['daily_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intakes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('daily_unit_id', sa.Integer(), nullable=False, comment='日単位のデータのID'),
    sa.Column('food_name', sa.String(length=20), nullable=False, comment='食事名'),
    sa.Column('calorie', sa.String(length=4), nullable=False, comment='カロリー'),
    sa.Column('protein', sa.String(length=2), nullable=False, comment='タンパク質'),
    sa.ForeignKeyConstraint(['daily_unit_id'], ['daily_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intakes')
    op.drop_table('exercises')
    op.drop_table('goals')
    op.drop_index('ix_user_date', table_name='daily_records')
    op.drop_table('daily_records')
    op.drop_table('body_profiles')
    op.drop_table('users')
    op.drop_table('user')
    # ### end Alembic commands ###
