"""usersのORMの修正、認証に対応した修正

Revision ID: cd8e8663b913
Revises: 69d5b46ed2ad
Create Date: 2026-08-15 11:55:57.184289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cd8e8663b913'
down_revision: Union[str, Sequence[str], None] = '69d5b46ed2ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'google_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'google_id',
               existing_type=sa.String(length=255),
               type_=mysql.INTEGER(),
               nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
