"""日付追加

Revision ID: d9bc796a8efb
Revises: 9d1dbb81af18
Create Date: 2026-07-23 11:07:12.111196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9bc796a8efb'
down_revision: Union[str, Sequence[str], None] = '9d1dbb81af18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('date', sa.Date(), nullable=False, comment='日付'))
    op.add_column('intakes', sa.Column('date', sa.Date(), nullable=False, comment='日付'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intakes', 'date')
    op.drop_column('exercises', 'date')
    # ### end Alembic commands ###
