"""体重の桁数変更

Revision ID: dff0ff504ada
Revises: 8be323ef4db4
Create Date: 2026-07-26 09:21:15.531460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dff0ff504ada'
down_revision: Union[str, Sequence[str], None] = '8be323ef4db4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('body_profiles', 'weight_kg',
               existing_type=mysql.VARCHAR(length=3),
               type_=sa.String(length=5),
               existing_comment='体重',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('body_profiles', 'weight_kg',
               existing_type=sa.String(length=5),
               type_=mysql.VARCHAR(length=3),
               existing_comment='体重',
               existing_nullable=False)
    # ### end Alembic commands ###
