"""add_tables

Revision ID: faef2e36ea83
Revises: a373b8f7501a
Create Date: 2026-03-15 04:05:01.119982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'faef2e36ea83'
down_revision: Union[str, Sequence[str], None] = 'a373b8f7501a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ユーザーID'),
    sa.Column('date', sa.Date(), nullable=False, comment='日付'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_user_date')
    )
    op.create_index('ix_user_date', 'daily_records', ['user_id', 'date'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('basal_calories', sa.String(4), nullable=False, comment='基礎代謝'),
    sa.Column('deficit', sa.String(4), nullable=False, comment='赤字カロリー'),
    sa.Column('protein', sa.String(3), nullable=False, comment='タンパク質'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('daily_unit_id', sa.Integer(), nullable=False, comment='日単位のデータのID'),
    sa.Column('exercise_name', sa.String(10), nullable=False, comment='運動名'),
    sa.Column('calories_burned', sa.String(3), nullable=False, comment='消費カロリー'),
    sa.ForeignKeyConstraint(['daily_unit_id'], ['daily_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intakes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('daily_unit_id', sa.Integer(), nullable=False, comment='日単位のデータのID'),
    sa.Column('food_name', sa.String(20), nullable=False, comment='食事名'),
    sa.Column('calorie', sa.String(4), nullable=False, comment='カロリー'),
    sa.Column('protein', sa.String(2), nullable=False, comment='タンパク質'),
    sa.ForeignKeyConstraint(['daily_unit_id'], ['daily_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='User ID(主キー)'),
    sa.Column('name', mysql.VARCHAR(length=20), nullable=False, comment='ユーザー名'),
    sa.PrimaryKeyConstraint('id'),
    comment='User',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='User',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('intakes')
    op.drop_table('exercises')
    op.drop_table('goals')
    op.drop_index('ix_user_date', table_name='daily_records')
    op.drop_table('daily_records')
    # ### end Alembic commands ###
